### PR TITLE
Allow for users to override index pattern for metrics

### PR DESCRIPTION
**Pull request by marc-sensenich**
### Fixes
- Allows for user overriding of index pattern via `kuberwatcher.yml`
- Updates runtime packages to latest versions
- Removes the deprecated package `elasticsearch-xpack`

### CODE REVIEW

**Review by Crazybus — CHANGES_REQUESTED** [review]
LGTM! Could you also add this new configuration option into the readme? https://github.com/elastic/kuberwatcher#configuration

Apart from that this all looks perfect! Thanks a lot for adding this in :)

**Comment by Crazybus** [comment]
jenkins test this please

**Comment by marc-sensenich** [comment]
@Crazybus updated the README in https://github.com/elastic/kuberwatcher/pull/9/commits/e039cd78a1d1a07dec8c6b3946b01a5645a36210

**Review by Crazybus — APPROVED** [review]

**Comment by Crazybus** [comment]
Thanks again for your great contribution :)

**Comment by marc-sensenich** [comment]
@Crazybus you're welcome! From a release perspective, what's that timeline going to look like?

**Comment by Crazybus** [comment]
Hey Marc!

I just did a new [release](https://github.com/elastic/kuberwatcher/releases/tag/6.5.4-1) which contains all of your contributions. 

`docker.elastic.co/kuberwatcher/kuberwatcher:6.5.4-1` is the matching docker image.

**Pull request merged**
